name: test-apitube

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Test APITube API
        env:
          APITUBE_API_KEY: ${{ secrets.APITUBE_API_KEY }}
        run: python -u test_apitube.py
